config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: ''
  root to: 'movies#index'
  resources :source_apis do
    post 'load_dump'
    post 'update_with_details'
    post 'load_actors'
  end
  resources :movies
  get 'overview' => 'movies#overview'
  get 'graph' => 'movies#graph'
  get 'data' => 'movies#data'
  post 'dump_genres' => 'genres#batch_create'
  post 'find_similar_movies' => 'movies#find_similar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/source_api.rb
class SourceApi
  include Mongoid::Document
  field :name, type: String
  field :access_url, type: String
  field :website, type: String
  field :default, type: Mongoid::Boolean
end

app/controllers/source_apis_controller.rb
class SourceApisController < ApplicationController
  before_action :set_source_api, only: [:show, :edit, :update, :destroy, :load_dump]
  before_action :authenticate_admin_user!

  def load_dump
    if @source_api.name == 'themoviedb-api'
      movies = DumpLoader.load
      Movie.batch_create(movies)
      redirect_to movies_path
    elsif @source_api.name == 'wiki'
      DumpLoader.update_via_wiki
    end
  end

  def update_with_details
    DumpLoader.update_with_details
    redirect_to movies_path
  end

  def load_actors
    DumpLoader.load_actors
    redirect_to movies_path
  end

  # GET /source_apis
  # GET /source_apis.json
  def index
    @source_apis = SourceApi.all
  end

  # GET /source_apis/1
  # GET /source_apis/1.json
  def show
  end

  # GET /source_apis/new
  def new
    @source_api = SourceApi.new
  end

  # GET /source_apis/1/edit
  def edit
  end

  # POST /source_apis
  # POST /source_apis.json
  def create
    @source_api = SourceApi.new(source_api_params)

    respond_to do |format|
      if @source_api.save
        format.html { redirect_to @source_api, notice: 'Source api was successfully created.' }
        format.json { render :show, status: :created, location: @source_api }
      else
        format.html { render :new }
        format.json { render json: @source_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_apis/1
  # PATCH/PUT /source_apis/1.json
  def update
    respond_to do |format|
      if @source_api.update(source_api_params)
        format.html { redirect_to @source_api, notice: 'Source api was successfully updated.' }
        format.json { render :show, status: :ok, location: @source_api }
      else
        format.html { render :edit }
        format.json { render json: @source_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_apis/1
  # DELETE /source_apis/1.json
  def destroy
    @source_api.destroy
    respond_to do |format|
      format.html { redirect_to source_apis_url, notice: 'Source api was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_api
      id = params[:id] || params[:source_api_id]
      @source_api = SourceApi.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_api_params
      params.require(:source_api).permit(:name, :access_url, :website, :default)
    end
end

app/helpers/source_apis_helper.rb
module SourceApisHelper
end

app/views/source_apis/_form.html.erb
<%= form_for(source_api) do |f| %>
  <% if source_api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source_api.errors.count, "error") %> prohibited this source_api from being saved:</h2>

      <ul>
      <% source_api.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :access_url %>
    <%= f.text_field :access_url %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :default %>
    <%= f.check_box :default %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_apis/edit.html.erb
<h1>Editing Source Api</h1>

<%= render 'form', source_api: @source_api %>

<%= link_to 'Show', @source_api %> |
<%= link_to 'Back', source_apis_path %>

app/views/source_apis/index.html.erb
<h2 class="title is-2">Source APIs</h2>


<div class="tile is-ancestor">
  <div class="tile is-parent">
    <article class="tile is-child notification box is-info">
      <%= link_to 'Get some genres', dump_genres_path, method: :post, class: "subtitle button is-info is-inverted is-outlined" %>
      <p>From TMDB</p>
    </article>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child box">
      <%= link_to 'Load actors', source_api_load_actors_path(SourceApi.find_by(name: 'themoviedb-api')), method: :post, class: "subtitle button is-warning is-inverted is-outlined" %>
      <p>From TMDB</p>
    </article>
  </div>
</div>

<div class="tile is-ancestor">
  <div class="tile is-parent">
    <article class="tile is-child box notification is-primary">
      <%= link_to 'Load the dump', source_api_load_dump_path(SourceApi.find_by(name: 'themoviedb-api')), method: :post, class: "subtitle button is-primary is-inverted is-outlined" %>
      <p>Only overview info</p>
    </article>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child box notification is-danger">
      <%= link_to 'Load more data', source_api_load_dump_path(SourceApi.find_by(name: 'wiki')), method: :post, class: "subtitle button is-danger is-inverted is-outlined" %>
      <p>Find and save available descriptions from wiki. This could take a while.</p>
    </article>
  </div>
</div>


<div class="tile is-ancestor">
  <div class="tile is-parent">
    <article class="tile is-child notification box is-warning">
      <%= link_to 'More details about movies', source_api_update_with_details_path(SourceApi.find_by(name: 'themoviedb-api')), method: :post, class: "subtitle button is-warning is-inverted is-outlined" %>
      <p>Updates from TMDB</p>
    </article>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child box">
      <%= link_to 'Assosiate movies', find_similar_movies_path, method: :post, class: "subtitle button is-warning is-inverted is-outlined" %>
      <p>via external R script</p>
    </article>
  </div>
</div>

app/views/source_apis/new.html.erb
<h1>New Source Api</h1>

<%= render 'form', source_api: @source_api %>

<%= link_to 'Back', source_apis_path %>

app/views/source_apis/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @source_api.name %>
</p>

<p>
  <strong>Access url:</strong>
  <%= @source_api.access_url %>
</p>

<p>
  <strong>Website:</strong>
  <%= @source_api.website %>
</p>

<p>
  <strong>Default:</strong>
  <%= @source_api.default %>
</p>

<%= link_to 'Edit', edit_source_api_path(@source_api) %> |
<%= link_to 'Back', source_apis_path %>