config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: ''
  root to: 'movies#index'
  resources :source_apis do
    post 'load_dump'
    post 'update_with_details'
    post 'load_actors'
  end
  resources :movies
  get 'overview' => 'movies#overview'
  get 'graph' => 'movies#graph'
  get 'data' => 'movies#data'
  post 'dump_genres' => 'genres#batch_create'
  post 'find_similar_movies' => 'movies#find_similar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>What2watch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <nav class="level has-shadow">
      <div class="level-left">
        <%= link_to '🍿', root_path, class: "nav-item", style: "font-size: 48px; padding: 0 20px;" %>
        <%= link_to '🌌', overview_path, class: "nav-item", style: "font-size: 48px; padding: 0 20px;" %>
        <%= link_to '❄️', graph_path, class: "nav-item", style: "font-size: 48px; padding: 0 20px;" %>
        <div class="field has-addons">
          <%= form_tag(movies_path, method: :get, class: "level-item") do %>
              <%= text_field_tag :search, params[:search], class: 'input', placeholder: @rand_title %>
              <%= submit_tag 'Search', title: nil, class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
      <div class="level-right">

        <%= link_to '💾', source_apis_path, class: "level-item" if current_user.try(:admin?) %>

        <% if user_signed_in? %>
            <%= link_to 'Profile', edit_user_registration_path, class: "level-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "level-item" %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "level-item" %>
            <%= link_to "Sign in", new_user_session_path, class: "level-item" %>
        <% end %>
      </div>
    </nav>
    <br>

    <% if notice %>
        <div class="notification is-info"><%= notice %></div>
    <% end %>
    <% if alert %>
        <div class="notification is-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

  </body>
</html>